### ISSUE TITLE
[Bug] Unable to drag TitleBar when maximized

### ISSUE THREAD

**Issue by nlogozzo** [Simnico99/MicaWPF#15]
After updating to 3.1.16, if the MicaWindow is maximized and you try to drag the title bar down to move it around, the window stays maximized and doesn't move.
On 3.1.15, the TitleBar drags correctly.

Also, 3.1.16 's TitleBar is much bigger in height compared to 3.1.15 and I think the 3.1.15 height is better as it matches every other Windows applications' TitleBar height.

**Comment by Simnico99** [comment]
Normally it is dictated by the CaptionHeight the issue I had with the old titlebar is this
![image](https://user-images.githubusercontent.com/80013536/168364108-a07638a5-c3f4-41da-9821-45d2224550b1.png)

The button is not the same size for some reason (It is the one by Windows)

I will take A look at what I can do.
Maybe I will revert the change for now you can Use 3.1.15

**Comment by nlogozzo** [comment]
That issue with the maximize button is an issue across all Win32 apps that use the dark mode title bar provided by the undocumented api. If you look at file explorer it has the same issue.

**Comment by nlogozzo** [comment]
And the custom buttons a big issue I'll get used to it haha...some apps such as MS Office have the same big custom caption buttons. However the critical issue is being unable to drag the TitleBar to move the window when maximized.

**Comment by nlogozzo** [comment]
Also, even for the title bar height if we can define the CaptionHeight property on the window to make it as big or small as we choose and the custom caption buttons will scale with it that'll work

**Comment by Simnico99** [comment]
I'll add an option probably for the Legacy (Windows TitleBar) and the New TitleBar I will see when I come back from work

**Comment by nlogozzo** [comment]
FYI: see https://stackoverflow.com/questions/24654845/dragging-custom-window-title-bar-from-top-when-maximized-does-not-work for dragging with custom TitleBar

**Comment by Simnico99** [comment]
Here is my plan:
Add 2 new Property to the Windows:
- TitleBarHeight (Will scale de button properly)
- TitleBarType

And an enum for the TitleBarType:
```CSharp
enum TitleBarType
{
WinUI,
Win32 (Default)
}
```

**Comment by Simnico99** [comment]
I will start working on It once I am back from work.

**Comment by Simnico99** [comment]
Now with the new one it is responsive to the TitleBarHeight

```xaml
TitleBarHeight="50"
TitleBarType="WinUI"
```
![image](https://user-images.githubusercontent.com/80013536/168490938-47cd307f-ab52-44dc-af21-056c8958bf6d.png)

If you want the old one:
```xaml
TitleBarType="Win32"
```
![image](https://user-images.githubusercontent.com/80013536/168490983-60168689-7402-4fe1-836c-a2a94c3d7ec2.png)

(P.S I've tested and dragging the titlebar works in both cases)

**Comment by Simnico99** [comment]
Pushed version 3.1.17

**Comment by nlogozzo** [comment]
I'm getting this error from my splash screen:
![image](https://user-images.githubusercontent.com/17648453/168493542-3075ad83-b619-472f-8751-f1e7118eeeeb.png)
```
  | StackTrace | "   at System.Runtime.CompilerServices.CastHelpers.Unbox(Void* toTypeHnd, Object obj)\r\n   at MicaWPF.Controls.MicaWindow.get_TitleBarType()\r\n   at MicaWPF.Controls.MicaWindow.OnSourceInitialized(EventArgs e)\r\n   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)\r\n   at System.Windows.Window.CreateSourceWindowDuringShow()\r\n   at System.Windows.Window.SafeCreateWindowDuringShow()\r\n   at System.Windows.Window.ShowHelper(Object booleanBox)\r\n   at System.Windows.Window.Show()\r\n   at System.Windows.Window.ShowDialog()\r\n   at NickvisionApp.App.OnStartup(StartupEventArgs e) in C:\\Users\\nlogo\\OneDrive\\Documents\\Programming\\NickvisionApp\\NickvisionApp\\App.xaml.cs:line 15\r\n   at System.Windows.Application.<.ctor>b__1_0(Object unused)\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)\r\n   at System.Windows.Threading.DispatcherOperation.InvokeImpl()\r\n   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)\r\n   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)" | string
```
Defined as
```xml
<mica:MicaWindow x:Class="NickvisionApp.Views.SplashDialogView"
                 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                 xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
                 xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                 xmlns:behaviors="http://schemas.microsoft.com/xaml/behaviors"
                 xmlns:mica="clr-namespace:MicaWPF.Controls;assembly=MicaWPF"
                 xmlns:hc="https://handyorg.github.io/handycontrol"
                 xmlns:nickvision="clr-namespace:Nickvision.WPF.Controls;assembly=Nickvision.WPF"
                 xmlns:local="clr-namespace:NickvisionApp.Views"
                 mc:Ignorable="d" Name="Dialog" Width="500" Height="300" ShowInTaskbar="False" 
                 WindowStartupLocation="CenterScreen" ResizeMode="NoResize" SystemBackdropType="Mica">              
```
Just from upgrading to 3.1.19, not changing anything.

**Comment by Simnico99** [comment]
I am a complete Idiot forgot to change this when I copy pasted my code:
```Csharp
//Is Right now:
    public TitleBarType TitleBarType
    {
        get => (TitleBarType)GetValue(MarginMaximizedProperty);
        set => SetValue(MarginMaximizedProperty, value);
    }
    
//Should be:
    public TitleBarType TitleBarType
    {
        get => (TitleBarType)GetValue(TitleBarTypeProperty);
        set => SetValue(TitleBarTypeProperty, value);
    }
```

**Comment by nlogozzo** [comment]
> I am a complete Idiot forgot to change this when I copy pasted my code:
> 
> ```Csharp
> 
> //Is Right now:
> 
>     public TitleBarType TitleBarType
> 
>     {
> 
>         get => (TitleBarType)GetValue(MarginMaximizedProperty);
> 
>         set => SetValue(MarginMaximizedProperty, value);
> 
>     }
> 
>     
> 
> //Should be:
> 
>     public TitleBarType TitleBarType
> 
>     {
> 
>         get => (TitleBarType)GetValue(TitleBarTypeProperty);
> 
>         set => SetValue(TitleBarTypeProperty, value);
> 
>     }
> 
> ```

Haha no worries we've all had our fair share of copy paste bugs

**Comment by Simnico99** [comment]
Pushing version 3.1.20 right now

**Comment by nlogozzo** [comment]
Ok just updated.
With `TitleBarType="Win32"` everything works fine no problems.
However, when I change `TitleBarType="WinUI"` and have `WindowState="Maximized"`, the window enters a fullscreen mode which hides the taskbar and prevents dragging the window down from the TitleBar to exit maximize mode. 
Whereas, with Win32 TitleBar mode, when `WindowState="Maximized"`, the window sits above the TaskBar, and dragging the window down from the TitleBar works as expected.

**Comment by Simnico99** [comment]
> Ok just updated. With `TitleBarType="Win32"` everything works fine no problems. However, when I change `TitleBarType="WinUI"` and have `WindowState="Maximized"`, the window enters a fullscreen mode which hides the taskbar and prevents dragging the window down from the TitleBar to exit maximize mode. Whereas, with Win32 TitleBar mode, when `WindowState="Maximized"`, the window sits above the TaskBar, and dragging the window down from the TitleBar works as expected.

I've found out why in WPF there is a known issue that a WindowStyle="None" goes over the taskbar I've added a Hook now it shouldn't go over it.

**Comment by Simnico99** [comment]
Pushing 3.1.21 now

**Comment by nlogozzo** [comment]
Ok, taskbar issue is fixed. 
However, when using `TitleBarType="WinUI"` and having the window maximized, there is this weird extra padding around the window.

Not maximized:
![image](https://user-images.githubusercontent.com/17648453/168498834-36d723b7-9c24-466e-9cc3-5564a0786eba.png)

Maximized:
![image](https://user-images.githubusercontent.com/17648453/168498839-86217575-42d2-4a87-9be6-c6a4d13ec5f1.png)

Using Win32 TitleBar and Maximized:
![image](https://user-images.githubusercontent.com/17648453/168498877-cc51618c-c6f1-44dc-b64c-31c68b3c225a.png)

**Comment by Simnico99** [comment]
Ah probably the compensation I needed to add to the Win32 mode I will disable it for WinUI mode

**Comment by Simnico99** [comment]
Fixed the padding
![image](https://user-images.githubusercontent.com/80013536/168499462-338bc9bf-7e13-4316-9d95-ab6a19c479ea.png)

**Comment by Simnico99** [comment]
Pushing version 3.1.22

**Comment by nlogozzo** [comment]
Um...with updating to 3.1.22, the padding issue still occurs when using WinUI TitleBar. But now for both maximized and not maximized.

Not Maximized:
![image](https://user-images.githubusercontent.com/17648453/168500695-71eb18a8-c91b-4c35-9864-edad5e20337c.png)

Win32 Not Maximized:
![image](https://user-images.githubusercontent.com/17648453/168500729-14ea757d-2583-49a0-837f-2cb447ab12a1.png)

Maximized:
![image](https://user-images.githubusercontent.com/17648453/168500706-45516370-6005-4c77-bf08-11864dd1233b.png)

Win32 Maximized:
![image](https://user-images.githubusercontent.com/17648453/168500745-e4cec2b1-433f-4ba9-89d9-29bb2e5faaf5.png)

**Comment by Simnico99** [comment]
I've tried now with a controls that goes right to the edge the padding should be gone now
Pushing version 3.2.23

**Comment by nlogozzo** [comment]
Ok figured out the issue.

So with `TitleBarType="WinUI"` and `WindowState="Normal"`, yes the padding is gone. However, when  `WindowState="Maximize"` in the Window XAML, then the padding is there and doesn't go away even when the window is out of maximize.

**Comment by nlogozzo** [comment]
Also, I have a dual-monitor setup and when the TitleBar type is WinUI, the maximized window doesn't cover the taskbar on the primary monitor, however, when the window is moved to my second monitor and maximized again, the window will cover the taskbar on the second monitor.

**Comment by Simnico99** [comment]
I figured the issues.
It was checking the WindowState only on update now it looks for it when it changes and when it starts.
For dual monitors i've figured how to fix it pushing update 3.1.24 now.

**Comment by Simnico99** [comment]
No problem thx for your contribution to be honest I wouldn't have noticed most of the bugs you submitted!

**Comment by nlogozzo** [comment]
Padding fixed in 3.1.24

**Comment by nlogozzo** [comment]
However, the dual monitor situation has not.

My primary monitor is 1920x1080 and my secondary monitor is 2048x1152. 
Moving the application from my primary monitor to the secondary monitor with 3.1.24 causes the window on the second monitor to still cover the task bar and by stretched out and overlaps back onto the primary monitor as such:
![image](https://user-images.githubusercontent.com/17648453/168506982-b92b8659-cff6-4c32-9d5f-68f4b1e35437.png)

**Comment by Simnico99** [comment]
Weard how it works on my 3 monitor
![ce1167ab08ee0363b9c660920ab692dd](https://user-images.githubusercontent.com/80013536/168507225-fab3d0d4-a560-470e-a904-3cdf8cea598c.gif)
s

**Comment by nlogozzo** [comment]
Are your 3 monitors all the same resolution? Could be when I move from my primary to secondary, the window isn't scaled to the higher resolution of the second.

**Comment by Simnico99** [comment]
Ah I think I found out why I am using the cursor position instead of the window position let me change that.

**Comment by Simnico99** [comment]
Pushing 3.1.25

**Comment by nlogozzo** [comment]
Waiting for the Nuget...funny how a little custom TaskBar can cause all these windowing issues

**Comment by Simnico99** [comment]
I should have tested it more rigorously before pushing the feature to production, Well this is my first big public project I will learn from my errors.

**Comment by nlogozzo** [comment]
Haha no worries, I completely understand. I have one too (https://github.com/nlogozzo/Nickvision.WPF) and I push out updates for 1 line code changes all the time lol that I just glossed over.

**Comment by nlogozzo** [comment]
Don't hate the messenger...
![image](https://user-images.githubusercontent.com/17648453/168508707-5787f9d5-87db-45ef-9f68-e7668ebb63f3.png)
(V3.1.25)
xD

**Comment by Simnico99** [comment]
> Don't hate the messenger... ![image](https://user-images.githubusercontent.com/17648453/168508707-5787f9d5-87db-45ef-9f68-e7668ebb63f3.png) (V3.1.25) xD
*Insert table flipping*
I will check my math

**Comment by Simnico99** [comment]
I will check from work tomorrow could be caused by the fact that your 2 monitors are not of the same size (I got 2 different size monitors at work.)

**Comment by nlogozzo** [comment]
Sounds good! Thanks!

**Comment by nlogozzo** [comment]
Status update?

**Comment by Simnico99** [comment]
Hello, sorry for the delay I catched a stomach flu

**Comment by nlogozzo** [comment]
Oh no! Hoping for a speedy recovery!! 
If your up for it, I was thinking maybe you can replicate the bug in your home machine by changing the resolution of one of the monitors 🤷🏻‍♂️
But only if you feel up to coding haha...no rush

**Comment by Simnico99** [comment]
It does the issue only if my MAIN monitor is a lower resolution than my second monitors.
I will investigate why:
![image](https://user-images.githubusercontent.com/80013536/169337435-59bc40c4-7245-4205-b7bb-049c82596921.png)

**Comment by nlogozzo** [comment]
Glad to see you are doing better :)
Let me download and test the update...

**Comment by nlogozzo** [comment]
All issues fixed. Everything works perfectly, thanks for all the work!
